### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [NA] Bumped the build number (if the version is unchanged)
* [NA] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raybellwaves** [comment]
@conda-forge-admin, please rerender

**Comment by nils-braun** [comment]
Woah! That was quick @raybellwaves ! You were even faster than the automatic one ;-) (sometimes I think it just takes some time, I do not know why).
Thank you so much for looking into it!

I think the only thing that prevents a clean build is to use the current correct sha265 hash of the package in meta.yml: e71ba25e1f24e208aa0c06c4b3bcc1db36e59b50b8260abcd7f18d71a7b944c7

**Comment by raybellwaves** [comment]
Failing at `ModuleNotFoundError: No module named 'tzlocal'
` https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=236118&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=15507. I'll add that package

**Comment by nils-braun** [comment]
Thanks for fixing and doing the version bump!

**Review by nils-braun — APPROVED** [review]

**Comment by raybellwaves** [comment]
np. should be good to merge.

**Pull request merged**
