### PR TITLE
Release `2022.10.1`

### PR DESCRIPTION
**Pull request by charlesbluca**
Still working out issues with the pip packaging/uploading process, but with the source distribution uploaded we can see if conda-forge builds are working as expected.

cc @ayushdg 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by charlesbluca** [comment]
@conda-forge-admin, please rerender

**Comment by charlesbluca** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by ayushdg** [comment]
I wonder if there's a way to enable linux-aarch64 builds as well. For context the latest pypi builds also include support for linux-aarch64.

cc: @charlesbluca or @jakirkham in case you have any suggestions.

**Comment by jakirkham** [comment]
Was [automerge]( https://conda-forge.org/docs/maintainer/infrastructure.html#automerge ) enabled for this feedstock? Looks like the bot went ahead and merged an update ( https://github.com/conda-forge/dask-sql-feedstock/pull/47 ). If we don't want that happening, would suggest [disabling automerge]( https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-remove-bot-automerge )

**Comment by jakirkham** [comment]
> I wonder if there's a way to enable linux-aarch64 builds as well. For context the latest pypi builds also include support for linux-aarch64.

Would drop `arm64` from this skip and [re-render]( https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-rerender )

https://github.com/conda-forge/dask-sql-feedstock/blob/533dbaed9049fb0c15c9ddb5a29006ce24a08353/recipe/meta.yaml#L13

**Comment by charlesbluca** [comment]
Yeah, the automerge was unintentional - will go ahead and disable.

> Would drop arm64 from this skip and [re-render](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-rerender)

That's already being done in this PR - perhaps we should merge this in and rebase https://github.com/conda-forge/dask-sql-feedstock/pull/45?

**Comment by charlesbluca** [comment]
@conda-forge-admin, please rerender

**Comment by ayushdg** [comment]
Ah it does look like linux-aarch64 builds would be enabled after merging in #45. I'm investigating the build failures there https://app.travis-ci.com/github/conda-forge/dask-sql-feedstock/jobs/585231754. But for the time being we should be good to go ahead and use this version of the recipe. 

Do we just directly merge this in or are some changes needed because of the auto merge from #47?

**Comment by charlesbluca** [comment]
> Do we just directly merge this in or are some changes needed because of the auto merge from https://github.com/conda-forge/dask-sql-feedstock/pull/47?

This should be good to merge in once CI is green, I resolved the conflicts from the automerge

**Review by ayushdg — APPROVED** [review]

**Comment by jakirkham** [comment]
Think we need to bump the build number since the bot's PR was already merged. Also will need to hot-fix the repodata

Ah didn't realize this wasn't already migrated. Rerunning the migrator as Ayush has done is probably the right way forward

**Comment by jakirkham** [comment]
Updated migrator in PR ( https://github.com/conda-forge/dask-sql-feedstock/pull/50 )

**Comment by jakirkham** [comment]
Automerge was disabled in PR ( https://github.com/conda-forge/dask-sql-feedstock/pull/49 )

Build number is being bumped in PR ( https://github.com/conda-forge/dask-sql-feedstock/pull/52 )

Repodata is being hot-fixed in PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/345 )

If one spots anything else missed, please let us know 🙂

**Pull request merged**
