### PR TITLE
Bump build number for 2022.10.1

### PR DESCRIPTION
**Pull request by charlesbluca**
Forgot to do this in #46 to get ahead of the automated release

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by charlesbluca** [comment]
@conda-forge-admin, please rerender

**Comment by charlesbluca** [comment]
Hmm it looks like packages with updated pinnings are seemingly being uploaded with build number 1 already:

https://anaconda.org/conda-forge/dask-sql/files

Assuming this is something that just gets done automatically when the build number hasn't been bumped but pinnings were updated? cc @jakirkham not sure if it's necessary to merge this PR anymore but will go ahead and update the pinnings for the older builds

**Comment by charlesbluca** [comment]
Closing this as packages with updated pinnings have been released automatically; following up with https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/345, and if we need to release a new build within this patch release for some reason let's just bump directly to build 2

**Comment by jakirkham** [comment]
Thanks Charles 🙏 It would still be good to merge this

**Pull request merged**
